services:
  backend:
    image: ghcr.io/remi-espie/autorenewpaybyphone/back:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/config.yaml:ro

  frontend:
    image: ghcr.io/remi-espie/autorenewpaybyphone/front:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
