[application]

# app (Project) Name
name = "front"

# Dioxus app Default Platform
# web, desktop, fullstack
default_platform = "web"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Auto Renew PayByPhone"

[web.watcher]

index_on_404 = true

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["./assets/bulma.min.css", "./assets/main.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[[web.proxy]]
backend = "http://localhost:3000/api/"
