name: Lint Rust package

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout project

      - uses: ./.github/actions/init
        name: Common Steps

      - name: Check formatting
        run: cargo fmt --check

      - name: Check linting
        run: cargo clippy -- -D warnings

  build-back:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        name: Checkout project

      - uses: ./.github/actions/init
        name: Common Steps

      - name: Build back
        run: cargo build -p back --release

  build-front:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        name: Checkout project

      - uses: ./.github/actions/init
        name: Common Steps

      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      - name: Build front
        run: cd front && dx build --web --release