name: Lint Rust package

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout project

      - uses: dtolnay/rust-toolchain@stable
        name: Install the Rust toolchain
        with:
          target: x86_64-unknown-linux-gnu, wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        name: Use cached dependencies and artifacts

      - name: Check formatting
        run: cargo fmt --check

      - name: Check linting
        run: cargo clippy -- -D warnings

  build-back:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Build back
        run: cargo build -p back --release

  build-front:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      - name: Build front
        run: cd front && dx build --web --release